name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          repository: YkzaGrg/BootCamp
          path: repositorio 

      - name: Construir imagen
        run: |
          docker image build --tag webserver3 .

      - name: Ejecutar contenedor
        run: |
          docker run -d --name servidor_web -v webvol:/var/www/html/ webserver3

      - name: Publicar imagen
        run: |
          docker tag webserver3:latest ykzagorgonita/desafio13:v4
          docker push ykzagorgonita/desafio13:v4

      - name: Test
        run: |
          curl http://localhost:8080
